command_node:
  ros__parameters:
    topic_name: "command"
    controller_name: "omni_controller/"
    set_point_list: 
      - start
      - move_for
      - straight
      - slow_down
      - move_for1
      - straight1
      - slow_down1
      - move_for2
      - straight2
      - slow_down2
      - move_for3
      - straight3
      - slow_down3
      - stop 
    start: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 0.0
    move_for: 
      vx: -0.075
      vy: -0.02
      omega: 0.0
      time: 1.0
    straight: 
      vx: -0.075
      vy: -0.02
      omega: 0.0
      time: 20.0
    slow_down: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 21.0
    move_for1: 
      vx: -0.075
      vy: 0.02
      omega: 0.0
      time: 22.0
    straight1: 
      vx: -0.075
      vy: 0.02
      omega: 0.0
      time: 42.0
    slow_down1: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 43.0
    move_for2: 
      vx: 0.075
      vy: -0.02
      omega: 0.0
      time: 44.0
    straight2: 
      vx: 0.075
      vy: -0.02
      omega: 0.0
      time: 64.0
    slow_down2: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 65.0
    move_for3: 
      vx: 0.075
      vy: 0.02
      omega: 0.0
      time: 66.0
    straight3: 
      vx: 0.075
      vy: 0.02
      omega: 0.0
      time: 86.0
    slow_down3: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 87.0
    stop: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 88.0