command_node:
  ros__parameters:
    topic_name: "motion_generator/simple_velocity_command"
    set_point_list: 
      - start
      - move_for
      - straight
      - move_for_1
      - straight_1
      - move_for_2
      - straight_2
      - slow_down
      - stop 
    start: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 0.0
    move_for: 
      vx: 0.15
      vy: 0.0
      omega: 0.0
      time: 1.0
    straight: 
      vx: 0.15
      vy: 0.0
      omega: 0.0
      time: 21.0
    move_for_1: 
      vx: 0.30
      vy: 0.0
      omega: 0.0
      time: 22.0
    straight_1: 
      vx: 0.30
      vy: 0.0
      omega: 0.0
      time: 42.0
    move_for_2: 
      vx: 0.45
      vy: 0.0
      omega: 0.0
      time: 43.0
    straight_2: 
      vx: 0.45
      vy: 0.0
      omega: 0.0
      time: 64.0
    slow_down: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 69.0
    stop: 
      vx: 0.0
      vy: 0.0
      omega: 0.0
      time: 70.0
    use_sim_time: true